import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { AuthProvider, useAuth } from "./context/AuthContext";
import { ProtectedRoute, PublicRoute } from "./components/auth/ProtectedRoute";
import { AppLayout } from "./components/layout/AppLayout";
import { Dashboard } from "./pages/Dashboard";
import { GradeAssignment } from "./pages/GradeAssignment";
import { Results } from "./pages/Results";
import { Analytics } from "./pages/Analytics";
import { Landing } from "./pages/Landing";
import { Login } from "./pages/Login";
import { Student } from "./pages/Student";
import { Professor } from "./pages/Professor";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "./components/ui/Card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./components/ui/Table";
import { Button } from "./components/ui/Button";
import { Input } from "./components/ui/Input";
import { Label } from "./components/ui/Label";
import { useState } from "react";

function ReportsView() {
  const recentReports = [
    { id: "r1", name: "Weekly Grading Summary", generatedBy: "System", date: "2026-08-15" },
    { id: "r2", name: "Class Performance - PHY101", generatedBy: "Demo Teacher", date: "2026-08-10" },
    { id: "r3", name: "Low Confidence Questions", generatedBy: "AI Assistant", date: "2026-08-08" },
  ];

  return (
    <div className="p-8 space-y-6">
      <h1 className="text-2xl font-bold">Reports</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Total Reports</CardTitle>
            <CardDescription>Generated this month</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">12</CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Published</CardTitle>
            <CardDescription>Available to students</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">8</CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Pending</CardTitle>
            <CardDescription>Awaiting review</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">4</CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>Download or preview generated reports</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentReports.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-medium">{r.name}</TableCell>
                  <TableCell>{r.generatedBy}</TableCell>
                  <TableCell>{r.date}</TableCell>
                  <TableCell className="text-right">
                    <Button variant="ghost">View</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

function SettingsView() {
  const { user, updateProfile } = useAuth();
  const [autoReports, setAutoReports] = useState(true);
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(user?.name ?? "");
  const [email, setEmail] = useState(user?.email ?? "");

  const saveProfile = () => {
    updateProfile({ name: name.trim(), email: email.trim() });
    setEditing(false);
  };

  return (
    <div className="p-8 space-y-6">
      <h1 className="text-2xl font-bold">Settings</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between w-full">
              <div>
                <CardTitle>Account</CardTitle>
                <CardDescription>Profile information</CardDescription>
              </div>
              <div>
                {!editing ? (
                  <Button variant="outline" onClick={() => setEditing(true)}>Edit Profile</Button>
                ) : (
                  <div className="flex gap-2">
                    <Button variant="ghost" onClick={() => { setEditing(false); setName(user?.name ?? ""); setEmail(user?.email ?? ""); }}>Cancel</Button>
                    <Button onClick={saveProfile}>Save</Button>
                  </div>
                )}
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {!editing ? (
              <>
                <div className="text-sm">Name: <span className="font-medium">{user?.name ?? "-"}</span></div>
                <div className="text-sm">Email: <span className="font-medium">{user?.email ?? "-"}</span></div>
                <div className="text-sm">Role: <span className="font-medium">{user?.role ?? "-"}</span></div>
              </>
            ) : (
              <div className="space-y-3">
                <div>
                  <Label>Name</Label>
                  <Input value={name} onChange={(e) => setName(e.target.value)} />
                </div>
                <div>
                  <Label>Email</Label>
                  <Input value={email} onChange={(e) => setEmail(e.target.value)} />
                </div>
                <div className="text-xs text-muted-foreground">Role cannot be changed here.</div>
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>AI & Reports</CardTitle>
            <CardDescription>Preferences for report generation</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-medium">Auto-generate weekly reports</div>
                <div className="text-xs text-muted-foreground">The system will create a summary report every week.</div>
              </div>
              <div>
                <Button variant={autoReports ? "default" : "outline"} onClick={() => setAutoReports(!autoReports)}>
                  {autoReports ? "Enabled" : "Disabled"}
                </Button>
              </div>
            </div>

            <div>
              <div className="text-sm font-medium">Report detail level</div>
              <div className="text-xs text-muted-foreground">Choose how much detail to include in generated reports.</div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/landing" element={<PublicRoute><Landing /></PublicRoute>} />
          <Route path="/login" element={<PublicRoute><Login /></PublicRoute>} />
          <Route path="/student-login" element={<Login role="Student" />} />
          <Route path="/professor-login" element={<Login role="Professor" />} />
          
          <Route element={<ProtectedRoute><AppLayout /></ProtectedRoute>}>
            <Route index element={<Dashboard />} />
            <Route path="grade" element={<GradeAssignment />} />
            <Route path="upload" element={<GradeAssignment step={2} />} />
            <Route path="results" element={<Results />} />
            <Route path="analytics" element={<Analytics />} />
            <Route path="student" element={<Student />} />
            <Route path="professor" element={<ProtectedRoute allowedRoles={["Professor"]}><Professor /></ProtectedRoute>} />
            
            {/* Placeholders for other routes */}
            <Route path="assignments" element={<div className="p-8"><h1 className="text-2xl font-bold mb-4">Assignments</h1><p>Assignment management view coming soon.</p></div>} />
            <Route path="students" element={<Student />} />
            <Route path="reports" element={<ReportsView />} />
            <Route path="settings" element={<SettingsView />} />
            <Route path="support" element={<div className="p-8"><h1 className="text-2xl font-bold mb-4">Help & Support</h1><p>Knowledge base coming soon.</p></div>} />
          </Route>
        </Routes>
      </Router>
    </AuthProvider>
  );
}

export default App;
