import { BrowserRouter as Router, Routes, Route, Navigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { api, ApiError, type ClassRecord, type User } from "./lib/api";
import { AuthProvider, useAuth } from "./context/AuthContext";
import { ProtectedRoute, PublicRoute } from "./components/auth/ProtectedRoute";
import { AppLayout } from "./components/layout/AppLayout";
import { GradeAssignment } from "./pages/GradeAssignment";
import { Results } from "./pages/Results";
import { Analytics } from "./pages/Analytics";
import { Landing } from "./pages/Landing";
import { Login } from "./pages/Login";
import { Student } from "./pages/Student";
import { Professor } from "./pages/Professor";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "./components/ui/Card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./components/ui/Table";
import { Button } from "./components/ui/Button";
import { Input } from "./components/ui/Input";

function ReportsView() {
  const recentReports = [
    { id: "r1", name: "Weekly Grading Summary", generatedBy: "System", date: "2026-08-15" },
    { id: "r2", name: "Class Performance - PHY101", generatedBy: "Demo Teacher", date: "2026-08-10" },
    { id: "r3", name: "Low Confidence Questions", generatedBy: "AI Assistant", date: "2026-08-08" },
  ];

  return (
    <div className="p-8 space-y-6">
      <h1 className="text-2xl font-bold">Reports</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Total Reports</CardTitle>
            <CardDescription>Generated this month</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">12</CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Published</CardTitle>
            <CardDescription>Available to students</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">8</CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Pending</CardTitle>
            <CardDescription>Awaiting review</CardDescription>
          </CardHeader>
          <CardContent className="p-6 text-3xl font-bold">4</CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>Download or preview generated reports</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Date</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentReports.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-medium">{r.name}</TableCell>
                  <TableCell>{r.generatedBy}</TableCell>
                  <TableCell>{r.date}</TableCell>
                  <TableCell className="text-right">
                    <Button variant="ghost">View</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}

function SettingsView() {
  const { user } = useAuth();

  return (
    <div className="p-8 space-y-6">
      <h1 className="text-2xl font-bold">Settings</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between w-full">
              <div>
                <CardTitle>Account</CardTitle>
                <CardDescription>Profile information</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="text-sm">Name: <span className="font-medium">{user?.name ?? "-"}</span></div>
            <div className="text-sm">Email: <span className="font-medium">{user?.email ?? "-"}</span></div>
            <div className="text-sm">Role: <span className="font-medium">{user?.role ?? "-"}</span></div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>AI & Reports</CardTitle>
            <CardDescription>Preferences for report generation</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <div className="text-sm font-medium">Auto-generate weekly reports</div>
                <div className="text-xs text-muted-foreground">The system will create a summary report every week.</div>
              </div>
              <div>
              <span className="text-sm text-muted-foreground">Preferences are not available yet.</span>
              </div>
            </div>

            <div>
              <div className="text-sm font-medium">Report detail level</div>
              <div className="text-xs text-muted-foreground">Choose how much detail to include in generated reports.</div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function StudentsView() {
  const [classes, setClasses] = useState<ClassRecord[]>([]);
  const [classId, setClassId] = useState("");
  const [students, setStudents] = useState<User[]>([]);
  const [studentId, setStudentId] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const refreshStudents = async (id: number) => { try { setStudents(await api.classes.students(id)); setError(""); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not load students."); } };
  useEffect(() => { api.classes.list().then((items) => { setClasses(items); if (items[0]) setClassId(String(items[0].id)); }).catch((cause) => setError(cause instanceof ApiError ? cause.message : "Could not load classes.")); }, []);
  useEffect(() => { if (classId) void refreshStudents(Number(classId)); }, [classId]);
  const addStudent = async () => { try { await api.classes.addStudent(Number(classId), Number(studentId)); setStudentId(""); setNotice("Student added to class."); await refreshStudents(Number(classId)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not add student."); } };
  const removeStudent = async (id: number) => { try { await api.classes.removeStudent(Number(classId), id); setNotice("Student removed from class."); await refreshStudents(Number(classId)); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "Could not remove student."); } };
  return <div className="space-y-6 p-8"><h1 className="text-2xl font-bold">Class Students</h1><Card><CardHeader><CardTitle>Manage Class Membership</CardTitle><CardDescription>Students must be enrolled before submitting class assignments.</CardDescription></CardHeader><CardContent className="space-y-4"><select aria-label="Class" className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={classId} onChange={(e) => setClassId(e.target.value)}><option value="">Select a class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}{item.section ? ` · ${item.section}` : ""}</option>)}</select><div className="flex gap-2"><Input aria-label="Student ID" type="number" min="1" placeholder="Student user ID" value={studentId} onChange={(e) => setStudentId(e.target.value)} /><Button disabled={!classId || !studentId} onClick={() => void addStudent()}>Add Student</Button></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}{notice && <p role="status" className="text-sm text-emerald-600">{notice}</p>}<div className="space-y-2">{students.map((student) => <div key={student.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{student.name}</p><p className="text-sm text-muted-foreground">{student.email} · ID {student.id}</p></div><Button variant="outline" size="sm" onClick={() => void removeStudent(student.id)}>Remove</Button></div>)}{classId && students.length === 0 && <p className="text-sm text-muted-foreground">No students enrolled in this class.</p>}</div></CardContent></Card></div>;
}

function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/landing" element={<PublicRoute><Landing /></PublicRoute>} />
          <Route path="/login" element={<PublicRoute><Login /></PublicRoute>} />
          <Route path="/student-login" element={<PublicRoute><Login role="Student" /></PublicRoute>} />
          <Route path="/professor-login" element={<PublicRoute><Login role="Professor" /></PublicRoute>} />
          
          <Route element={<ProtectedRoute><AppLayout /></ProtectedRoute>}>
            <Route index element={<RoleHome />} />
            <Route path="grade" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><GradeAssignment /></ProtectedRoute>} />
            <Route path="upload" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><GradeAssignment /></ProtectedRoute>} />
            <Route path="results" element={<Results />} />
            <Route path="analytics" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><Analytics /></ProtectedRoute>} />
            <Route path="student" element={<ProtectedRoute allowedRoles={["STUDENT"]}><Student /></ProtectedRoute>} />
            <Route path="professor" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><Professor /></ProtectedRoute>} />
            
            {/* Placeholders for other routes */}
            <Route path="assignments" element={<div className="p-8"><h1 className="text-2xl font-bold mb-4">Assignments</h1><p>Assignment management view coming soon.</p></div>} />
            <Route path="students" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><StudentsView /></ProtectedRoute>} />
            <Route path="reports" element={<ProtectedRoute allowedRoles={["PROFESSOR"]}><ReportsView /></ProtectedRoute>} />
            <Route path="settings" element={<SettingsView />} />
            <Route path="support" element={<div className="p-8"><h1 className="text-2xl font-bold mb-4">Help & Support</h1><p>Knowledge base coming soon.</p></div>} />
          </Route>
        </Routes>
      </Router>
    </AuthProvider>
  );
}

function RoleHome() {
  const { user } = useAuth();
  return <Navigate to={user?.role === "PROFESSOR" ? "/professor" : "/student"} replace />;
}

export default App;
