package com.smartgrading.backend.service.impl;
import com.smartgrading.backend.dto.*; import com.smartgrading.backend.entity.*; import com.smartgrading.backend.exception.*; import com.smartgrading.backend.repository.*; import com.smartgrading.backend.service.ClassService; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class ClassServiceImpl implements ClassService {
 private final ClassRepository classes; private final SubjectRepository subjects; private final ClassStudentRepository members; private final UserRepository users; private final AccessControlService access;
 public ClassServiceImpl(ClassRepository c,SubjectRepository s,ClassStudentRepository m,UserRepository u,AccessControlService a){classes=c;subjects=s;members=m;users=u;access=a;}
 public ClassResponse create(ClassRequest r){User p=access.professor();ClassEntity c=new ClassEntity();c.setName(r.name());c.setSection(r.section());c.setSubject(subjects.findById(r.subjectId()).orElseThrow(()->new ResourceNotFoundException("Subject not found")));c.setProfessor(p);return ClassResponse.from(classes.save(c));}
 @Transactional(readOnly=true) public List<ClassResponse> all(){User u=access.current();List<ClassEntity> found=u.getRole()==Role.PROFESSOR?classes.findByProfessorId(u.getId()):members.findByStudentId(u.getId()).stream().map(ClassStudent::getClassEntity).toList();return found.stream().map(ClassResponse::from).toList();}
 @Transactional(readOnly=true) public ClassResponse get(Integer id){User u=access.current();ClassEntity c=access.classById(id);if(u.getRole()==Role.PROFESSOR&&!c.getProfessor().getId().equals(u.getId()))throw new AccessDeniedException("You do not own this class");if(u.getRole()==Role.STUDENT&&!access.isEnrolled(id,u.getId()))throw new AccessDeniedException("You are not enrolled in this class");return ClassResponse.from(c);}
 public ClassResponse update(Integer id,ClassRequest r){ClassEntity c=access.ownedClass(id);c.setName(r.name());c.setSection(r.section());c.setSubject(subjects.findById(r.subjectId()).orElseThrow(()->new ResourceNotFoundException("Subject not found")));return ClassResponse.from(classes.save(c));}
 public void delete(Integer id){classes.delete(access.ownedClass(id));}
 @Transactional(readOnly=true) public List<UserResponse> students(Integer id){access.ownedClass(id);return members.findByClassEntityId(id).stream().map(ClassStudent::getStudent).map(UserResponse::from).toList();}
 public void addStudent(Integer cid,Integer sid){ClassEntity c=access.ownedClass(cid);User s=users.findById(sid).orElseThrow(()->new ResourceNotFoundException("Student not found"));if(s.getRole()!=Role.STUDENT)throw new IllegalArgumentException("User must have STUDENT role");ClassStudentId key=new ClassStudentId(cid,sid);if(members.existsById(key))throw new UserAlreadyExistsException("Student is already enrolled");members.save(new ClassStudent(c,s));}
 public void removeStudent(Integer cid,Integer sid){access.ownedClass(cid);ClassStudentId key=new ClassStudentId(cid,sid);if(!members.existsById(key))throw new ResourceNotFoundException("Class membership not found");members.deleteById(key);}
}
