package com.smartgrading.backend.service.impl;
import com.smartgrading.backend.dto.*; import com.smartgrading.backend.entity.*; import com.smartgrading.backend.exception.*; import com.smartgrading.backend.repository.*; import com.smartgrading.backend.service.QuestionService; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class QuestionServiceImpl implements QuestionService { private final QuestionRepository questions; private final AccessControlService access; public QuestionServiceImpl(QuestionRepository q,AccessControlService a){questions=q;access=a;}
 public QuestionResponse create(QuestionRequest r){return create(r.assignmentId(),r);}
 public QuestionResponse create(Integer assignmentId,QuestionRequest r){if(!assignmentId.equals(r.assignmentId()))throw new IllegalArgumentException("Assignment id does not match request");Assignment a=access.ownedAssignment(assignmentId);if(questions.existsByAssignmentIdAndQuestionNumber(assignmentId,r.questionNumber()))throw new UserAlreadyExistsException("Question number already exists for this assignment");Question q=new Question();q.setAssignment(a);apply(q,r);return QuestionResponse.from(questions.save(q));}
 @Transactional(readOnly=true) public List<QuestionResponse> forAssignment(Integer id){Assignment a=access.assignmentById(id);User u=access.current();if(u.getRole()==Role.PROFESSOR&&!a.getClassEntity().getProfessor().getId().equals(u.getId()))throw new AccessDeniedException("You do not own this assignment");if(u.getRole()==Role.STUDENT&&!access.isEnrolled(a.getClassEntity().getId(),u.getId()))throw new AccessDeniedException("You are not enrolled in this class");return questions.findByAssignmentIdOrderByQuestionNumber(id).stream().map(QuestionResponse::from).toList();}
 public QuestionResponse update(Integer id,QuestionRequest r){Question q=questions.findById(id).orElseThrow(()->new ResourceNotFoundException("Question not found"));access.ownedAssignment(q.getAssignment().getId());if(!q.getAssignment().getId().equals(r.assignmentId()))throw new IllegalArgumentException("A question cannot be moved to another assignment");if(!q.getQuestionNumber().equals(r.questionNumber())&&questions.existsByAssignmentIdAndQuestionNumber(r.assignmentId(),r.questionNumber()))throw new UserAlreadyExistsException("Question number already exists for this assignment");apply(q,r);return QuestionResponse.from(questions.save(q));}
 public void delete(Integer id){Question q=questions.findById(id).orElseThrow(()->new ResourceNotFoundException("Question not found"));access.ownedAssignment(q.getAssignment().getId());questions.delete(q);}
 private void apply(Question q,QuestionRequest r){q.setQuestionNumber(r.questionNumber());q.setQuestionText(r.questionText());q.setMaxMarks(r.maxMarks());q.setExpectedAnswer(r.expectedAnswer());q.setMarkingCriteria(r.markingCriteria());}
}
