package com.smartgrading.backend.service.impl;
import com.smartgrading.backend.dto.*; import com.smartgrading.backend.entity.*; import com.smartgrading.backend.exception.*; import com.smartgrading.backend.repository.*; import com.smartgrading.backend.service.SubmissionService; import java.util.List; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class SubmissionServiceImpl implements SubmissionService {
 private final SubmissionRepository submissions; private final StudentAnswerRepository answers; private final AssignmentRepository assignments; private final QuestionRepository questions; private final AiEvaluationRepository evaluations; private final GradeRepository grades; private final AccessControlService access;
 public SubmissionServiceImpl(SubmissionRepository s,StudentAnswerRepository a,AssignmentRepository as,QuestionRepository q,AiEvaluationRepository e,GradeRepository g,AccessControlService ac){submissions=s;answers=a;assignments=as;questions=q;evaluations=e;grades=g;access=ac;}
 public SubmissionResponse create(Integer assignmentId,SubmissionRequest r){User student=access.student();Assignment a=access.assignmentById(assignmentId);if(a.getStatus()!=AssignmentStatus.ACTIVE)throw new IllegalArgumentException("Assignment is not accepting submissions");if(!access.isEnrolled(a.getClassEntity().getId(),student.getId()))throw new AccessDeniedException("You are not enrolled in this class");if(submissions.existsByAssignmentIdAndStudentId(assignmentId,student.getId()))throw new UserAlreadyExistsException("A submission already exists for this assignment");Submission s=new Submission();s.setAssignment(a);s.setStudent(student);s.setFileName(r.fileName());s.setFilePath(r.filePath());s.setStatus(SubmissionStatus.SUBMITTED);return SubmissionResponse.from(submissions.save(s));}
 @Transactional(readOnly=true) public SubmissionResponse get(Integer id){return SubmissionResponse.from(access.readableSubmission(id));}
 @Transactional(readOnly=true) public List<SubmissionResponse> byAssignment(Integer id){access.ownedAssignment(id);return submissions.findByAssignmentId(id).stream().map(SubmissionResponse::from).toList();}
 @Transactional(readOnly=true) public List<SubmissionResponse> byStudent(Integer id){User u=access.current();if(u.getRole()==Role.STUDENT&&!u.getId().equals(id))throw new AccessDeniedException("You cannot access another student's submissions");if(u.getRole()==Role.PROFESSOR)throw new AccessDeniedException("Use the assignment submissions endpoint");return submissions.findByStudentId(id).stream().map(SubmissionResponse::from).toList();}
 @Transactional(readOnly=true) public List<StudentAnswerResponse> answers(Integer sid){Submission s=access.readableSubmission(sid);return answers.findBySubmissionId(s.getId()).stream().map(StudentAnswerResponse::from).toList();}
 public StudentAnswerResponse answer(Integer sid,StudentAnswerRequest r){Submission s=access.readableSubmission(sid);if(!s.getStudent().getId().equals(access.student().getId()))throw new AccessDeniedException("This is not your submission");if(s.getStatus()!=SubmissionStatus.SUBMITTED)throw new IllegalArgumentException("Submission is no longer editable");Question q=questions.findById(r.questionId()).orElseThrow(()->new ResourceNotFoundException("Question not found"));if(!q.getAssignment().getId().equals(s.getAssignment().getId()))throw new IllegalArgumentException("Question does not belong to this assignment");if(answers.existsBySubmissionIdAndQuestionId(sid,q.getId()))throw new UserAlreadyExistsException("Answer already exists for this question");StudentAnswer a=new StudentAnswer();a.setSubmission(s);a.setQuestion(q);a.setAnswerText(r.answerText());return StudentAnswerResponse.from(answers.save(a));}
 public StudentAnswerResponse updateAnswer(Integer answerId,AnswerUpdateRequest r){StudentAnswer a=access.answerById(answerId);User u=access.student();if(!a.getSubmission().getStudent().getId().equals(u.getId()))throw new AccessDeniedException("You cannot modify another student's answer");if(a.getSubmission().getStatus()!=SubmissionStatus.SUBMITTED)throw new IllegalArgumentException("Submission is no longer editable");a.setAnswerText(r.answerText());return StudentAnswerResponse.from(answers.save(a));}
 public SubmissionResponse transition(Integer id,SubmissionStatus target){Submission s=access.submissionById(id);access.ownedAssignment(s.getAssignment().getId());boolean valid=switch(s.getStatus()){case SUBMITTED->target==SubmissionStatus.PROCESSING;case PROCESSING->target==SubmissionStatus.GRADED&&hasCompleteEvaluation(s);case GRADED->target==SubmissionStatus.REVIEWED;case REVIEWED->false;};if(!valid)throw new IllegalArgumentException("Invalid submission status transition");s.setStatus(target);return SubmissionResponse.from(submissions.save(s));}
 private boolean hasCompleteEvaluation(Submission s){List<StudentAnswer> submittedAnswers=answers.findBySubmissionId(s.getId());if(submittedAnswers.isEmpty())return false;return submittedAnswers.stream().allMatch(a->evaluations.existsByAnswerId(a.getId())&&grades.existsByAnswerId(a.getId()));}
}
